# Generated by Django 6.0.4 on 2026-04-20 03:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_reply_message_remove_reply_user_patientqurey_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientQurey',
            new_name='PatientQuery',
        ),
    ]
