# Generated by Django 6.0.4 on 2026-04-20 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_patientquery_user_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientquery',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='api.conversation'),
        ),
    ]
