# Generated by Django 6.0.4 on 2026-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_patientquery_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='analization',
            field=models.TextField(blank=True),
        ),
    ]
