# Generated by Django 6.0.4 on 2026-04-21 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_conversation_analization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconsultation',
            name='query',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aiconsultation', to='api.patientquery'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='New Conversation', max_length=300),
        ),
    ]
